name: Test

on:
  push:
    branches: ["master"]

jobs:
  test:
    # где запускать
    runs-on: ubuntu-latest
    # что делать
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
            path: |
              ~/.m2/repository
              ~/.gradle/caches
            key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/build.gradle') }}
            restore-keys: |
              ${{ runner.os }}-${{ github.workflow }}-
      # используем джаву
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      # используем selenoid, для ui тестов
      - uses: Xotabu4/selenoid-github-action@v2
      # запуск тестов
     # - run: gradle compileTestJava
      - run: gradle clean test --tests TextBoxTest -Dselenide.remote=http://localhost:4444/wd/hub
      # подключение Allure
      # скачиваем историю тестов
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # генерируем отчет
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
         # allure_report: allure-report
          allure_history: allure-history
      # публикуем отчет
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history